config/routes.rb
Invoicexpress::Application.routes.draw do
  
  match 'welcome' => 'home#welcome'
  match 'debug'   => 'home#debug'
  match 'setup'   => 'home#setup'
  match 'help'    => 'help#index'
  match 'wizard'  => 'wizard#step1'
  match 'trouble' => 'home#trouble'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  resources :invoices do
    member do
      get 'send_email'
    end
  end

  resources :webhooks
  resources :shops

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  around_filter :shopify_session, :except => 'welcome'

  def welcome
    current_host = "#{request.host}#{':' + request.port.to_s if request.port != 80}"
    @callback_url = "http://#{current_host}/login"
  end

  def trouble

  end

  # get latest orders
  def index
    begin
      init_shop
      @orders = ShopifyAPI::Order.paginate per: 6, page: params[:page], params: {:order => "created_at DESC"}
      order_ids   = @orders.map(&:id)
      @db_invoices  = @shop.invoices.where(:order_id => order_ids)
    rescue Timeout::Error
      redirect_to trouble_path
    end
  end

  def setup
    begin
      @shop     = Shop.where(:store_url => ShopifyAPI::Shop.current.myshopify_domain).first
    rescue Timeout::Error
      redirect_to trouble_path
    end
  end

  def debug
    @shop     = Shop.where(:store_url => ShopifyAPI::Shop.current.myshopify_domain).first
    @hooks    = ShopifyAPI::Webhook.all
    @webhooks = Webhook.where(:shop_url=> ShopifyAPI::Shop.current.myshopify_domain).page params[:page]
  end

  private
  def init_shop
    #debugger
    if Shop.where(:store_url => ShopifyAPI::Shop.current.myshopify_domain).exists?

      @shop=Shop.where(:store_url => ShopifyAPI::Shop.current.myshopify_domain).first

      if session["shopify"] && session["shopify"].token != @shop.token
        @shop.token=session["shopify"].token
        @shop.save
      end
      init_webhooks
    else

      @shop           = Shop.new(:name => ShopifyAPI::Shop.current.name, :store_url => ShopifyAPI::Shop.current.myshopify_domain)
      @shop.token     = session["shopify"].token if session["shopify"]
      @shop.email     = ShopifyAPI::Shop.current.email
      @shop.store_id  = ShopifyAPI::Shop.current.id
      @shop.save

      init_webhooks
      session[:shop] = @shop.name
      redirect_to wizard_path()
    end
  end

  def init_webhooks
    #change this in production!
    #address=""
    if Rails.env.development?
      address="https://thinkorange.pagekite.me/webhooks"
    elsif Rails.env.staging?
      address="http://shopinvoicexpress.herokuapp.com/webhooks"
    else
      address="http://invoicexpress-shopify.herokuapp.com/webhooks"
    end


    exist_webhook = ShopifyAPI::Webhook.find :all, :params => {:address=>address}
    if exist_webhook && exist_webhook.size>0
      logger.debug("oh Webhook already exists")
    else
      webhook = ShopifyAPI::Webhook.create(:format => "json",  :topic => "orders/paid", :address => address)
      if webhook.valid?
        logger.debug("oh Webhook invalid: #{webhook.errors}")
      else
        logger.debug('Created webhook')
      end
    end

  end

end

app/helpers/home_helper.rb
module HomeHelper

end

app/views/home/debug.html.haml
%br
%section#tables
  %header
    %h1 Webhooks
  
  %ul
  - @hooks.each do |hook| 
    %li= hook.address
    %li= hook.topic


  -if @webhooks.blank?
    .row-fluid
      .span12
        .alert.alert-block
          %h2.alert-heading Nothing to see here.
  
  -else
    %table.table.full-section.table-hover
      %thead
        %tr
          %th Order no
          %th Created at
          %th Invoice id
          %th Params
      %tbody
      - @webhooks.each do |webhook| 
        %tr
          %td.primary
            = link_to webhook.order_id, "https://#{shop_session.url}/admin/orders/#{webhook.order_id}", :target => 'blank'
          %td
            = webhook.created_at.strftime("%d %b %Y: %Hh %Mm")
          %td
            = webhook.invoice_id
          %td
            =  webhook.params

  = paginate @webhooks, :theme=>'twitter-bootstrap'

app/views/home/index.html.haml
%br

%section#tables
  %header
    .pull-right
      %a.btn{ :href=> "#", :id=>'tourhome'} Tour
    %h1 Recent Orders

  -if @orders.blank?
    .row-fluid
      .span12
        .alert.alert-block
          %h4.alert-heading Welcome
          %p Your store doesn't have any orders.

  -else
    %table#orders_table.table.full-section.table-hover
      %thead
        %tr
          %th Order
          %th Customer
          %th Payment Status
          %th Fulfillment
          %th Invoice
          %th Total
          %th Action
      %tbody
      - @orders.each do |order|
        - db_invoice= @db_invoices.select { |dbinvoice| dbinvoice.order_id == order.id }.first
        %tr
          %td.primary
            = link_to order.name, "https://#{shop_session.url}/admin/orders/#{order.id}", :target => 'blank'
          %td
            =customer_name_helper(order)
          %td
            %span.label{:class=>orderStatus(order)}
              = order.financial_status
          %td
            %span.label{:class=>orderFulfilmentStatus(order)}
              = orderFulfilmentLabel(order)
          %td
            - if db_invoice
              %span.label.label-success
                Yes
            - else
              %span.label.label-warning
                No
          %td
            = order.total_price
            = order.currency
          %td
            - unless db_invoice
              = link_to 'Create Invoice', new_invoice_path(:order_id=>order.id), :class=>'btn btn-success'
            - else
              %a{:href=>"https://#{@shop.invoice_user}.invoicexpress.net/invoices/#{db_invoice.invoice_id}", :target=>'blank', :class=>'btn btn-success'} Open in InvoiceXpress

    = paginate @orders, :theme=>'twitter-bootstrap'

app/views/home/old.index.html.erb
<header class="jumbotron">
  <div class="inner">
    <div class="container">
      <h1 style="letter-spacing:-3px; margin-bottom:20px;">Where do I start?</h1>
      <p class="lead">An <strong>intro</strong> to using the Shopify App Template<br/>
      including information on the <strong>Shopify API</strong> and <strong>Bootstrap,</strong><br/>
      just to get the ball rolling.</p>
    </div><!-- /container -->
  </div>
</header>

<div class="row">
  <div class="span3">
    <div class="well">  
      <h3>Check out the <code>home_controller</code></h3>
      <hr style="margin:2px 0 7px"/>
      <p>The controller in this demo application fetches the newest 5 orders and products and makes them available as instance variables <code>@orders</code> and <code>@products</code></p>
    
      <br/>
    
      <h3>Take a look at <code>index.html.erb</code></h3>
      <hr style="margin:2px 0 7px"/>
      <p>Index is the Ruby template you are currently viewing. Have a look at the markup and Ruby code to see how the Shopify API is being used. It's located at <code>views/home/index.html.erb</code></p>
    </div>
    
    <h3>Additional Docs</h3>
    <p>You can become an expert pretty quickly by reading up on these docs:</p>
    
    <ul>
      <li>
        <%= link_to 'API documentation', 'http://www.shopify.com/developers/api/' %>
        <span class="note">Learn what you can do with the Shopify API</span>
      </li><br/>
      <li>
        <%= link_to 'Bootstrap documentation', 'http://twitter.github.com/bootstrap/' %>
        <span class="note">Find out what you can do with Twitter Bootstrap</span>
      </li><br/>
      <li>
        <%= link_to 'Wiki', 'http://wiki.shopify.com/' %>
        <span class="note">Get more information and share your knowledge</span>
      </li><br/>
      <li>
        <%= link_to 'Forum', 'http://forums.shopify.com/community' %>
        <span class="note">Ask questions and see what others already wanted to know</span>
      </li>
    </ul>
  
    <hr/>
  
    <h3>Once you're ready</h3>
  
    <p>We'd love to see what you create using the Shopify API. You can keep up to date on the latest and greatest via the <%= link_to 'Shopify API Twitter Account', 'http://www.twitter.com/shopifyapi' %>. You can also read the latest information on the <%= link_to 'API Publishing Page', 'http://www.shopify.com/developers/publishing/' %>.</p>
    
    <br/>
    
    <a href="https://twitter.com/shopifyapi" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @shopifyapi</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div> <!-- span3 / left-column -->


  <div class="span8 offset1">
    <h2>Recent orders</h2>
  
    <% if @orders.blank? %>
      <table class="table table-striped">
        <tr>
          <td><em>There are no orders in your store.</em></td>
        </tr>
      </table>
    
    <% else %>
  
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Order</th>
            <th>Placed by</th>
            <th>Paid</th>
            <th>Fulfillment</th>
            <th>Total</th>
          </tr>
        </thead>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.name, "https://#{shop_session.url}/admin/orders/#{order.id}", :target => 'blank' %></td>
          <td><%= order.billing_address.name %></td>
          <td>
            <span class="label  <% if order.financial_status  == 'paid' %>label-success<% end %> <% if order.financial_status  == 'pending' %>label-warning<% end %> <% if order.financial_status  == 'refunded' %>label-important<% end %>"><%= order.financial_status %>
            </span>
          </td>
          <td>
            <% if !order.fulfillment_status %>
            <span class="label">Not Fulfilled</span>
            <% else %>
            <span class="label label-success">Fulfilled</span>
            <% end %>
          </td>
          <td><%= order.total_price %> <%= order.currency %></td>
        </tr>
      <% end %>
      </table>
      
    <% end %>
    
    <br/>
    
    <h2>New Products</h2>
    
    <div class="accordion" id="accordion">      
      
      <% if @products.blank? %>
      
        <div class="accordion-group">
          <div class="accordion-heading">
            <em>There are no products in your store.</em>
          </div>
        </div>
      
      <% else %>
      
        <%  @products.each_with_index do |product, index| %>
          <div class="accordion-group">
            <div class="accordion-heading">
              
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#<%= product.id %>">
                <%= product.title %> <span class="pull-right muted"><%= product.price_range %> <%= shop_session.shop.currency %></span>
              </a>
            </div>
        
            <div id="<%= product.id %>" class="accordion-body collapse <% if index == 1 %>in<% end %>">
              <div class="accordion-inner">
                
                <% if !product.images.empty? %>
                  <div class="polaroid">
                    <%= link_to image_tag(product.images.first.medium), '#modal-'+product.id.to_s, :'data-toggle' => 'modal' %>
                  </div>
                <% end %>
                
                <p><strong>Type:</strong> <%= product.product_type %></p>
                <p><strong>Vendor:</strong> <%= product.vendor %></p>
                <p><%= raw(product.body_html) %></p><br/>
                <% if product.published_at != nil %>
                <p class="muted">Published at <%= Time.parse(product.published_at).strftime("%H:%M on %m/%d/%Y") %></p>
                <% end %>
                <p><%= link_to raw('View in your Shopify Admin <i class="icon-chevron-right" style="opacity:.25"></i>'), "https://#{shop_session.url}/admin/products/#{product.id}", :target => 'blank', :class => 'btn btn-primary' %></p>
              </div>
              
            </div>
          </div>
          
          <div class="modal hide fade" id="modal-<%= product.id %>" style="display:none;">
            <div class="modal-header">
              <a class="close" data-dismiss="modal">×</a>
              <h3><%= product.title %></h3>
            </div>
            <div class="modal-body" >
              <% if !product.images.empty? %>
                <%= image_tag product.images.first.large %>
              <% end %>
            </div>
          </div>
        <% end %>
      
      <% end %>
      
    </div> <!-- accordion -->
  </div> <!-- span8 / right-column -->
</div>

app/views/home/setup.html.haml
%br
%section#forms
  .pull-right
    %a.btn{ :href=> "#", :id=>'toursetup'} Help
  .page-header
    %h1 Setup
  .row-fluid
    .span12
      = semantic_form_for @shop, :html => { :class=>'form-vertical'} do |f| 
        .tab-content
          #api.tab-pane.active
            .row-fluid
              .span8
                = f.inputs do 
                  = f.input :invoice_user, :required => true, :input_html => {:class=>'input-xlarge'}, :hint=> 'Your InvoiceXpress User. Ex: http://SUBDOMAIN.invoicexpress.net <a href="#how1" id="showme1" class="btn btn-mini btn-info">Help</a>'.html_safe
                  = f.input :invoice_api, :required => true, :input_html => {:class=>'input-xlarge'}, :hint=>'Your InvoiceXpress API Key. Ex: 00asdasdasdsasd1 <a href="#how2" id="showme2" class="btn btn-mini btn-info">Help</a>'.html_safe
                  = render :partial=> "/wizard/select_country", :locals=>{:f=>f}

                  = f.input :finalize_invoice ,  :as=> :select, :collection => options_for_select({ "Draft" => false, "Final" => true }, @shop.finalize_invoice), :wrapper_html => {:class=>'stupid_checklabel'}, :include_blank => false, :label=>'Invoice State'
                  = f.input :auto_send_email ,  :as => :radio,  :include_blank => false,  :wrapper_html => {:class=>'stupid_checklabel'}, :label=>'Send by e-mail', :input_html=>{:rel=>'tooltip', :'data-placement'=>'right', :'data-original-title'=>"In order to send email to customer, the invoice must be in Final state."  }
              .span4
                = render :partial=>'/wizard/help'

        %br
        = f.actions do 
          = f.action :submit, :as => :button, :label=>'Save information', :button_html =>{:class=>'btn btn-large btn-success', :disable_with => 'Wait...' }
          = link_to "Cancel", root_path, :class => 'btn btn-large'
         

app/views/home/trouble.html.haml
.wizard.hero-unit
  %h1 Woopsie Daisy 
  %p
    We're having trouble connecting to the Shopify API. But don't worry it should be just temporary. 
  %p
    %a.btn.btn-large.btn-success{:href=>"#{root_path}", :target=>'_blank'} Go to Home