config/routes.rb
Invoicexpress::Application.routes.draw do
  
  match 'welcome' => 'home#welcome'
  match 'debug'   => 'home#debug'
  match 'setup'   => 'home#setup'
  match 'help'    => 'help#index'
  match 'wizard'  => 'wizard#step1'
  match 'trouble' => 'home#trouble'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  resources :invoices do
    member do
      get 'send_email'
    end
  end

  resources :webhooks
  resources :shops

  root :to => 'home#index'

end

app/views/layouts/_messages.html.haml
-if flash.count>0
  .row-fluid
    .span12
      %br
      - flash.each do |name, msg|
        %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
          %a.close{"data-dismiss" => "alert"} &#215;
          = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.erb
<%= link_to 'InvoiceXpress', '/', :class => 'brand' %>
<span class="tagline">a Invoice App for Shoppify. <a href="http://www.invoicexpress.pt">Read more.</a></span>
<% if shop_session %>
<div class="nav-collapse collapse" id="main-menu">
  <div class="auth pull-right">
      <img class="avatar" src="/assets/littke.png">
      <span class="name"><%= shop_session.url%></span><br/>
      <span class="links">
         <%= link_to raw('Storefront'), "http://"+shop_session.url, :target => 'blank' %>
         <%= link_to raw('Admin'), "http://"+shop_session.url+"/admin", :target => 'blank' %>
         <%= link_to raw('Logout'), logout_path, :method => :delete %>
      </span>
  </div>
</div>
<%end%>
 

app/views/layouts/_navigation.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to image_tag("logo_main.png", :alt=>"invoiceXpress"), root_path, :class => 'brand'

      - if shop_session
        .nav-collapse
          %ul.nav
            %li{:class=>"#{active_nav_class('home', 'index')}"}
              = link_to 'Orders', root_path, :id=>'menu_orders'
            %li{:class=>"#{active_nav_class('invoices')}"}
              =link_to 'Invoices', invoices_path, :id=>'menu_invoices'
            %li{:class=>"#{active_nav_class('home', 'setup')}"}
              =link_to 'Setup', '/setup', :id=>'menu_setup'
            %li{:class=>"#{active_nav_class('home', 'help')}"}
              =link_to 'Help', '/help', :id=>'menu_help'

        %ul#menu_settings.nav.pull-right
          %li.dropdown
            = link_to raw(shop_session.shop.name.to_s+' <b class="caret"></b>'), "https://#{shop_session.url}", :class => 'shop_name dropdown-toggle', :'data-toggle' => 'dropdown', :'data-target' => '#'
            %ul.dropdown-menu
              %li= link_to "Store", "http://"+shop_session.url, :target => 'blank'
              %li= link_to 'Shopify Admin', "http://"+shop_session.url+"/admin", :target => 'blank'
              - if @shop
                %li= link_to 'InvoiceXpress', "https://#{@shop.invoice_user}.invoicexpress.net/", :target => 'blank'
              %li.divider
              %li= link_to 'Logout', logout_path, :method => :delete

app/views/layouts/_sidemenu.html.haml
%aside
  %nav
    %ul.nav
      %li.selected
        = link_to raw('<i class="icon-play"></i> Dashboard'), root_url
      %li
        = link_to raw('<i class="icon-th-list icon-white"></i> Orders'), '#'
      %li
        = link_to raw('<i class="icon-user icon-white"></i> Settings'), '#'
      %li
        = link_to raw('<i class="icon-retweet icon-white"></i> Documentation'), '#'
      %li
        = link_to raw('<i class="icon-retweet icon-white"></i> Help'), '#'

app/views/layouts/_validate_api.html.haml
- if !@shop.nil? && !@shop.invoicexpress_ready?
  %br
  .alert.alert-block.alert-danger
    %h2
      Attention Please!
      %a.btn.btn-large.btn-danger.pull-right{:href => "/setup"} Continue to Setup
    %p We need your InvoiceXpress API key in order to send invoices. Please update your information in the setup area.

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %title InvoiceXpress Shopify App
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/    
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag 'application'
    %link{:href => "/assets/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "/assets/shopify-57.png", :rel => "apple-touch-icon"}/
    %link{:href => "/assets/shopify-72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "/assets/shopify-114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/

    /[if lt IE 8]
      = stylesheet_link_tag "font-awesome-ie7.min.css", media: "all"
      / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  %body
    = render "layouts/navigation"
    
    .container
      .content
        = render "layouts/messages"
        - unless params[:action]=='setup' || params[:action]=='step1'
          = render "layouts/validate_api"

        = yield

      %footer
        %p 
          A Shopify app by
          %a{:href=>'http://www.invoicexpress.net', :target=>'blank'} InvoiceXpress
          | View the 
          %a{:href=>'http://www.invoicexpress.net', :target=>'blank'} Terms
          All rights reserved
    / /container
    = javascript_include_tag 'application'

app/views/layouts/old.application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Shopify Demo App</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  
  <!-- icons -->
  <link rel="shortcut icon" href="../assets/favicon.png">
  <link rel="apple-touch-icon" href="../assets/shopify-57.png">
  <link rel="apple-touch-icon" sizes="72x72" href="../assets/shopify-72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="../assets/shopify-114.png">
  
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body>
  
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        
        <%= link_to 'Shopify Demo App', '/', :class => 'brand' %>
        
        <% if shop_session %>
          <div class="nav-collapse">
            <ul class="nav">
              <li class='<%= active_nav_class('home', 'index') %>'><%= link_to 'Where to Start', '/' %></li>
              <li class='<%= active_nav_class('home', 'design') %>'><%= link_to 'Bootstrap Info', '/design' %></li>
            </ul>
          </div>
          
          <ul class="nav pull-right">
            <li class="dropdown">
              <%= link_to raw(shop_session.url+' <b class="caret"></b>'), "https://#{shop_session.url}", :class => 'shop_name dropdown-toggle', :'data-toggle' => 'dropdown', :'data-target' => '#' %>
              <ul class="dropdown-menu">
                <li><%= link_to raw('<i class="icon-home"></i> Storefront'), "http://"+shop_session.url, :target => 'blank' %></li>
                <li><%= link_to raw('<i class="icon-cog"></i> Shopify Admin'), "http://"+shop_session.url+"/admin", :target => 'blank' %></li>
                <li class="divider"></li>
                <li><%= link_to raw('<i class="icon-off"></i> Logout'), logout_path, :method => :delete %></li>
              </ul>
            </li>
          </ul>
        <% end %>
        
      </div>
    </div>
  </div>
  
  
  <div class="container">
    
    <div class="content">
      <%= yield %>
    </div>
    
    <footer>
      <p>A Shopify app by (company name here)</p>
    </footer>
    
  </div> <!-- /container -->
</body>
</html>